#! /bin/sh 
### BEGIN INIT INFO
# Provides:		blocklyMicropython	     		
# Required-Start:	$all $local_fs $network $remote_fs 		
# Required-Stop:     	$all
# Default-Start:	2 3 4 5	
# Default-Stop:		0 1 6
# Short-Description:	blocklyMicropython.
# Description:       	This service is used by blocklyMicropython.
### END INIT INFO

case "$1" in

  start)
    echo "starting blocklyMicropython"
	cd /home/pi/appnode/
	node server/servidor_service.js & 
;;

  stop)
    echo "stopping"  
  ;;

esac
exit 0
